version: "3.8"
services:
        frontend:
                build: ./frontend
                ports:
                        - target: 5000
                          published: 5000
                          protocol: tcp
                depends_on:
                        - "backend"
        backend:
                build: ./backend
                ports:
                        - target: 5001
                          published: 5001
                          protocol: tcp
                environment:
                        DATABASE_URI: ${DATABASE_URI}
                        SECRET_KEY: ${SECRET_KEY}
